services:
  postgres:
    image: postgres:15-alpine
    container_name: franchise-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d   # <-- теперь монтируется
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - franchise-network



  redis:
    image: redis:7-alpine
    container_name: franchise-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - franchise-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    container_name: franchise-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_ADDR=${REDIS_ADDR:-redis:6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://frontend:3000}
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL:-admin@admin.ru}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD:-qwerty}
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - franchise-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: development
    container_name: franchise-frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - franchise-network

volumes:
  postgres_data:
    driver: local

networks:
  franchise-network:
    driver: bridge